NAME = ft_ping

SRCS = 	srcs/main.c \
		srcs/ft_ping.c \
		srcs/socket.c \
		srcs/packet.c \
		srcs/checksum.c \
		srcs/receive.c \
		srcs/utils.c

OBJS = $(SRCS:.c=.o)
DEPS = $(SRCS:.c=.d)

CC = gcc
CFLAGS = -Wall -Wextra -Werror -MMD -MP
LDFLAGS =
RM = rm -f

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

# Include dependency files generated by -MMD. Ignore missing files.
-include $(DEPS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS) $(DEPS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
